### ISSUE TITLE
Research Mavlink-Compatabile Flight Controller

### ISSUE THREAD

**Issue by s-hliao** [RoboJackets/urc-drone#10]
It appears that Mavlink systems are the most commonly used flight controllers for research drones and have multiple projects using them integrated with ROS for drone flight commands. Note that DJI does not produce mavlink-compatible drones and as such cannot be programmed with standard ros libraries.

See the following: 

https://docs.px4.io/main/en/ros/ros2.html
https://ardupilot.org/dev/docs/ros.html
https://github.com/ctu-mrs/mrs_uav_system
https://github.com/mavlink/mavros

**Comment by a-stickan** [comment]
@s-hliao Is this issue relevant anymore?
