### ISSUE TITLE
Determine a suitable drone to buy

### ISSUE THREAD

**Issue by s-hliao** [RoboJackets/urc-drone#9]
Requirements:
+/- 1.5m hover accuracy (GPS)
Camera
Less than 5 kg
PX4/Olympe/Mavlink Flight controller
Battery life >= 25 min (will be cut down due to having to lift weight equal to battery)

See the following drones running PX4:
https://docs.px4.io/main/en/complete_vehicles/
https://px4.io/ecosystem/commercial-systems/
https://github.com/mavlink/mavros/blob/master/mavros/README.md

**Comment by a-stickan** [comment]
Drone decision made, [we are going with a M500](https://docs.modalai.com/m500-datasheet/).
